feat: add project structure
farukshin-n/java-explore-with-me pull request #2
Opened 2022-11-14 16:24 UTC by farukshin-n

first PR for tutor's check

2022-12-05 15:12 UTC, alexache requested changes

2022-12-05 15:12 UTC, alexache commented on ewm-service/pom.xml
> +            <version>5.0.0</version>
Версии должны быть указаны только в родительском модуле через dependencyManagement

2022-12-05 15:12 UTC, alexache commented on ewm-service/pom.xml
> +                <version>1.1.3</version>
Как и версии плагинов должны быть в родительском модуле

2022-12-05 15:12 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewmservice/client/StatsClient.java
> +public class StatsClient {
Очень хорошо сделано!

2022-12-05 15:12 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewmservice/controller/UserController.java
> +@Validated
Это не обязательно, если есть @restController и @Valid

2022-12-05 15:12 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewmservice/controller/event/EventController.java
> +        eventService.deleteEvent(eventId);
Здесь логгирование не нужно?

2022-12-05 15:12 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewmservice/dto/AdminUpdateEventRequest.java
> +    private String title;
Можно бы добавить валидаций полей

2022-12-05 15:12 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewmservice/model/Hit.java
> +public class Hit {
А зачем эта модель в основном модуле, а не в модуле статистики?

2022-12-05 15:12 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewmservice/model/Hit.java
> +    public boolean equals(Object o) {
Опасный путь определения equals/hashcode, тебе где-то нужен сет их этих обхектов? equals выглядит корректным, а вот на счет hashcode не уверен

2022-12-05 15:12 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewmservice/model/Location.java
> +        return Objects.equals(lat, location.lat) && Objects.equals(lon, location.lon);
Тут уже очень смущает, тоже есть сет их этих объектов? Если нет, то лучше не пытаться определять эти методы

2022-12-05 15:12 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewmservice/service/CompilationServiceImpl.java
> +            List<EventShortDto> events = getEventShortDtoList(compilation.getEvents());
(опционально) можно пожалуй в функциональном стиле написать

2022-12-05 15:12 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewmservice/service/CompilationServiceImpl.java
> +    public void unpinCompilation(Long compilationId) {
Можно бы переиспользовать соседний метод, сделав общий с аргументом пин/анпин

2022-12-05 15:12 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewmservice/service/CompilationServiceImpl.java
> +                int confirmedRequests = requestRepository.findAllByEvent_IdAndStatus(eventId,
Запрос к базе данных в  цикле - это не хорошо, надо бы одним запросом по списку событий

2022-12-05 15:12 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewmservice/service/EventServiceImpl.java
> +                    int confirmedRequests = requestRepository.findAllByEvent_IdAndStatus(events.get(i).getId(),
Еще один запрос к базе в цикле, нужно было делать одним запросом по списку событий

2022-12-05 15:12 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewmservice/service/EventServiceImpl.java
> +                int confirmedRequests = requestRepository.findAllByEvent_IdAndStatus(id,
Еще один запрос к базе в цикле

2022-12-05 15:12 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewmservice/service/EventServiceImpl.java
> +                int confirmedRequests = requestRepository.findAllByEvent_IdAndStatus(id,
И еще обращения в цикле

2022-12-05 15:12 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewmservice/service/mapper/EventMapper.java
> +        events.forEach(e -> result.add(toEventFullDto(e, confirmedRequests, views)));
(опционально) можно бы и дальше в функциональном стиле

2022-12-05 15:12 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewmservice/service/mapper/ParticipationRequestMapper.java
> +    public ParticipationRequest toRequest(ParticipationRequestDto dto) {
RequestMapper должен бы быть stateless и static без вызовов других классов

2022-12-05 18:37 UTC, farukshin-n commented on ewm-service/src/main/java/ru/practicum/ewmservice/model/Hit.java
> +public class Hit {
Случайно скопировалась, видимо...

2022-12-06 13:02 UTC, alexache requested changes

2022-12-06 13:02 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewmservice/service/compilation/CompilationServiceImpl.java
> +        if (compilation.getEvents().contains(event)) {
Лучше все же искать по id, а не по адресу объекта

2022-12-06 13:02 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewmservice/service/compilation/CompilationServiceImpl.java
> +        if (!compilation.getEvents().contains(event)) {
И здесь тоже лучше делать поик по айди

2022-12-06 18:17 UTC, alexache approved these changes

2022-12-06 19:42 UTC, merged